### ISSUE TITLE
env variable SKIP_LINK_PARSING  has no effect

### ISSUE THREAD

**Issue by PabTorre** [awslabs/aws-ai-qna-bot#25]
## Expected Behavior

When environement variable SKIP_LINK_PARSING is set to TRUE on QNA-master-1-master-********-Handler-1-***** function, responses can include URLs

## Actual Behavior

URL's are parsed and throw error as seen in logs below, instead of passing through, as expected from code on lambda/handler/lib/response.js line 38  

## Steps to Reproduce the Problem

  1. Set environment variable  SKIP_LINK_PARSING  = TRUE on the handler lambda. 
  2. Create test question where answer includes:  
`<a href="http://www.google.com">ask google!! </a>`
  3. Trigger question. 

## Specifications

  - Version: master 
  - Platform: Amazon Linux running on EC2 

## error log: 

{ DependencyFailedException: Invalid Lambda Response: Received invalid response from Lambda: Can not construct instance of GenericAttachment$Builder, problem: Attachment Url is not in range <1,2048>  at [Source: {"sessionAttributes":{"<String>":"STRING_VALUE","appContext":"{\"responseCard\":{\"version\":1,\"contentType\":\"application/vnd.amazonaws.card.generic\",\"genericAttachments\":[{\"title\":\"Additional Information\",\"attachmentLinkUrl\":\"http://www.google.com\\\">ask\"}]}}"},"dialogAction":{"type":"Close","fulfillmentState":"Fulfilled","message":{"contentType":"PlainText","content":" </p>\n\n <a href=\"  google!! </a>"},"responseCard":{"version":1,"contentType":"application/vnd.amazonaws.card.generic","genericAttachments":[{"title":"Additional Information","attachmentLinkUrl":"http://www.google.com\">ask"}]}}}; line: 1, column: 985]

**Comment by JohnCalhoun** [comment]
I have replicated this error on develop branch

**Comment by bobpskier** [comment]
Set the SKIP_LINK_PARSING=TRUE environment variable on the fulfillment lambda. The parsing occurs in this lambda. Alternatively you can use mark down syntax such as 

[ask google!!](http://www.google.com)

If using the lex-web-ui this allows the link to appear as a button and not be spoken back to the user as a sequence of characters when using voice mode. The processing when parsing is enabled, uses the responseCard with a genericAttachment are used to pass the link information back to the client.

**Comment by JohnCalhoun** [comment]
this is part of a larger issue addressed in #29,
closing this issue
