### ISSUE TITLE
Develop Branch: Content Designer UI - New Account sign up doesn't create functioning account. 

### ISSUE THREAD

**Issue by rstrahan** [awslabs/aws-ai-qna-bot#36]
## Expected Behavior

Content Designer UI should not allow public users to sign up for an account. Access to Content designer must be restricted to content administrators only.

Suugest we allow new accounts to be created only by an existing Admin user.
I.e. remove the 'sign up' feature on the login page, but add a new 'Add/remove users' feature accessible only to existing authorized users.

## Actual Behavior

Using the 'sign up' feature creates an account OK, but after logging in with the new account, Content designer doesn't work.

## Steps to Reproduce the Problem

  1. Use the 'sign up' link in the login page to create a new account
  2. Login and try to use that new account
 
![image](https://user-images.githubusercontent.com/10953374/33629744-252616f8-d9d3-11e7-956b-0d1409fd4e24.png)

## Specifications

  - Version:
  - Platform:

**Comment by JohnCalhoun** [comment]
Problem) cannt turn user signup off per client, is global for userpool. 

fix) added a template parameter to api-template to toggle if users can sign themselfs up. default is off.
