### ISSUE TITLE
Implement Alexa AMAZON.StopIntent

### ISSUE THREAD

**Issue by rstrahan** [awslabs/aws-ai-qna-bot#37]
## Expected Behavior

The Alexa skill associated with QnABot should support the Cancel intent to close the skill. 

## Actual Behavior

Currently the QnABot skill remains open until it times out, even after a cancel request, which can cause issues if user attempts to invoke another skill.

**Comment by JohnCalhoun** [comment]
-  add close intent to schema giving in designer ui instructions
- add implementation to fulfillment handler

**Comment by JohnCalhoun** [comment]
moving discussion to #47
