### ISSUE TITLE
Adding a "response_type" to the lambda handler causes an error

### ISSUE THREAD

**Issue by dontirun** [awslabs/aws-ai-qna-bot#64]
## Expected Behavior
adding the "response_type" key with a value of "redirect" will redo the elastisearch query with the edited parameters  

## Actual Behavior
adding the "response_type" key with a value of "redirect" causes the bot to be unable to process the message ("continue" works fine) 

## Steps to Reproduce the Problem

  1. Create a document with a lambda handler function
  2. Have the handler function add  a "response_type key" with value "redirect"
  3. trigger the document with a prompt

@JohnCalhoun

**Comment by JohnCalhoun** [comment]
I am concerned about this mechanism!
I am having difficulty implementing this as doing redirect within the handler is very un-natural. 
The core idea of the fulfillment function is modeled after the express webserver and express does not have this mechanism.

there are also problems that the redirect mechanism creates:
- infinite loop
- error handling and debuging 

I think it is easier and more straight forward to have the hook lambda do any sublimental logic needed, such as making its own ES request. 

I am inclined to remove the redirect behavior unless a compelling case can be made that:
- a use case requires it
- that use case cannot use the hook lambda for needed behavior

**Comment by JohnCalhoun** [comment]
we are no longer using this mechanism
